# Generated by Django 4.1.7 on 2023-04-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Hospitals",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("email", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "doctor_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("speciality", models.CharField(blank=True, max_length=100)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospitals",
                    ),
                ),
            ],
        ),
    ]
